#$schema: https://gitversion.net/schemas/6.3/GitVersion.configuration.json
# This sets the assembly versioning scheme. 'MajorMinorPatch' is standard.
assembly-versioning-scheme: MajorMinorPatch

# This defines the behavior for the 'next' branch, which you use as your develop branch.
branches:
  next:
    # ContinuousDeployment mode means a new version is generated for every commit on this branch.
    mode: ContinuousDeployment
    # This sets the pre-release tag for versions built from the 'next' branch (e.g., 1.1.0-next.1).
    label: next
    # When 'next' is merged into 'main', it will increment the Minor version number.
    # For example, if main is 1.0.0, the next release will be 1.1.0.
    increment: Minor
    # This ensures that the pre-release version numbers are based on the version of the main branch.
    track-merge-target: true
    # We want to increment the version on this branch.
    prevent-increment-of-merged-branch-version: false
    # This helps in creating stable pre-release package versions.
    is-pre-release-branch: true

  # This defines the behavior for the 'main' branch, your release branch.
  main:
    # ContinuousDeployment mode ensures every merge/commit to main gets a new version.
    mode: ContinuousDeployment
    # By setting the tag to an empty string, we ensure no pre-release label (like -alpha or -rc) is added.
    # This results in clean versions like 1.0.0, 1.1.0, etc.
    label: ''
    # This prevents the version from being bumped on the 'next' branch after it's merged into 'main'.
    prevent-increment-of-merged-branch-version: true
    # Marks this as a release branch.
    is-release-branch: true

  # This section configures the versioning for pull requests.
  pull-request:
    # ContinuousDeployment mode to get a build metadata for each build in the PR.
    mode: ContinuousDeployment
    # The pre-release tag will be 'pr' followed by the PR number (e.g., 1.1.0-pr.123).
    label: pr
    # The version increment strategy is inherited from the target branch ('next' in your case).
    increment: Inherit
