id = "01M3MC8S2P45DHDVRSTP0Q0XGQ"
name = "Vanilla Definitions"
description = "A collection of commonplace and simple definitions for materials, items, entities and biomes."

major_version = 0
minor_version = 1
patch_version = 0

author = "Nicholas Westerhausen"
author_id = "01M3MCS6WVJP5W6BHCSWWPVTG9"
