id = "01M3MC8S2PYXJKCF9E8K9301ZM"
name = "Frozen Bog"
description = "Subarctic peatland and muskeg with stagnant water over permafrost."
min_temperature = 0.0
max_temperature = 0.25
min_moisture = 0.5
max_moisture = 1.0
min_elevation = 0.0
max_elevation = 0.3
min_tectonic = 0.0
min_water_accumulation = 0.6
required_bedrock_formation = "Any"
