id = "01M3MAYQA6BB4XK4YN9QSECX2M"
name = "Tropical Rainforest"
description = "A dense, hot, and humid jungle environment."
min_temperature = 0.7
max_temperature = 1.0
min_moisture = 0.7
max_moisture = 1.0
min_elevation = 0.1
max_elevation = 0.5
min_tectonic = 0.0
min_water_accumulation = 0.0
required_bedrock_formation = "Any"
