id = "01M3MAYQA6S5S1DNA2YMJ2R99J"
name = "Woodland and Shrubland"
description = "A climate defined by hot, dry summers and mild, wet winters with dense shrubs and fire-resistant plants."
min_temperature = 0.4
max_temperature = 0.8
min_moisture = 0.2
max_moisture = 0.5
min_elevation = 0.1
max_elevation = 0.6
min_tectonic = 0.0
min_water_accumulation = 0.0
required_bedrock_formation = "Any"
