<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Package metadata -->
		<AssemblyName>UntitledRpgLogic.Extensions.Godot</AssemblyName>
		<PackageId>UntitledRpgLogic.Extensions.Godot</PackageId>
		<RootNamespace>UntitledRpgLogic.Extensions.Godot</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\UntitledRpgLogic.Infrastructure.Configuration\UntitledRpgLogic.Infrastructure.Configuration.csproj"/>
		<ProjectReference Include="..\UntitledRpgLogic.Infrastructure.Data.SQLite\UntitledRpgLogic.Infrastructure.Data.SQLite.csproj"/>
		<ProjectReference Include="..\UntitledRpgLogic.Networking\UntitledRpgLogic.Networking.csproj"/>
		<ProjectReference Include="..\UntitledRpgLogic.Services\UntitledRpgLogic.Services.csproj"/>
		<ProjectReference Include="..\UntitledRpgLogic.WorldGen\UntitledRpgLogic.WorldGen.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="GodotSharp"/>
		<PackageReference Include="ZLogger"/>
	</ItemGroup>

</Project>
