using UntitledRpgLogic.Core.Enums;
using UntitledRpgLogic.Core.Interfaces;
using UntitledRpgLogic.Core.Options;

namespace UntitledRpgLogic.Core.Configuration;

/// <summary>
///     Configuration for a Skill in the RPG logic.
/// </summary>
public class SkillDataConfig : ITomlConfig
{
    /// <summary>
    ///     Optional. If provided in TOML, this specific Guid will be used for the item.
    ///     If omitted, a new Guid will be generated by the game.
    /// </summary>
    public Guid? ExplicitId { get; init; }

    /// <summary>
    ///     Items will always have a name. This is required.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    ///     A short description of the item. This is optional and can be used to provide additional context or flavor text
    /// </summary>
    public string? Description { get; init; }

    /// <summary>
    ///     Options for the leveling behavior of the skill. If not provided, the default leveling options will be used.
    /// </summary>
    public LevelingOptions? LevelingOptions { get; init; }

    /// <inheritdoc />
    public ConfigType ConfigType => ConfigType.Skill;
}
