// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UntitledRpgLogic.Infrastructure.Data;

#nullable disable

namespace UntitledRpgLogic.Infrastructure.Data.Migrations
{
    [DbContext(typeof(RpgDbContext))]
    partial class RpgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.AppliedModifier", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EntityId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ModifierDefinitionId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Stacks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("ModifierDefinitionId");

                    b.ToTable("AppliedModifiers");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.Entity", b =>
                {
                    b.Property<byte[]>("Identifier")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.EntityInventory", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ItemInstanceId")
                        .HasColumnType("BLOB");

                    b.HasKey("EntityId", "ItemInstanceId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("EntityInventories");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.EntitySkills", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("InstancedSkillId")
                        .HasColumnType("BLOB");

                    b.HasKey("EntityId", "InstancedSkillId");

                    b.HasIndex("InstancedSkillId");

                    b.ToTable("EntitySkills");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.EntityStats", b =>
                {
                    b.Property<byte[]>("EntityId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("InstancedStatId")
                        .HasColumnType("BLOB");

                    b.HasKey("EntityId", "InstancedStatId");

                    b.HasIndex("InstancedStatId");

                    b.ToTable("EntityStats");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.InstancedSkill", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SkillDefinitionId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("SkillDefinitionId");

                    b.ToTable("InstancedSkills");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.InstancedStat", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<int>("ApparentValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("StatDefinitionId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("StatDefinitionId");

                    b.ToTable("InstancedStats");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.ItemDefinition", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<int>("ItemSubtype")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDurability")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Stackable")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemDefinitions");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.ItemInstance", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("CraftedById")
                        .HasColumnType("BLOB");

                    b.Property<int>("Durability")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ItemDefinitionId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PrimaryMaterialId")
                        .HasColumnType("BLOB");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemDefinitionId");

                    b.HasIndex("PrimaryMaterialId");

                    b.ToTable("ItemInstances");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.LinkedStats", b =>
                {
                    b.Property<byte[]>("DependentStatId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LinkedStatId")
                        .HasColumnType("BLOB");

                    b.Property<float>("Ratio")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("StatDefinitionId")
                        .HasColumnType("BLOB");

                    b.HasKey("DependentStatId", "LinkedStatId");

                    b.HasIndex("LinkedStatId");

                    b.HasIndex("StatDefinitionId");

                    b.ToTable("LinkedStats");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.MaterialDefinition", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaterialDefinitions");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.ModificationEffect", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<int>("FlatAmount")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<float>("PercentageOfMax")
                        .HasColumnType("REAL");

                    b.Property<bool>("Positive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModificationEffects");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.ModifierDefinition", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<float>("Duration")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsAdditive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMultiplicative")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LoseAllStacksOnExpiration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStacks")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ModifierEffectId")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ScalesOnBaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("StackEffectId")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ModifierEffectId");

                    b.HasIndex("StackEffectId");

                    b.ToTable("ModifierDefinitions");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.SkillDefinition", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PointsForFirstLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScalingCurve")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ScalingFactorA")
                        .HasColumnType("REAL");

                    b.Property<float>("ScalingFactorB")
                        .HasColumnType("REAL");

                    b.Property<float>("ScalingFactorC")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SkillDefinitions");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.StatDefinition", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<bool>("HasChangeableValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Variation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StatDefinitions");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.AppliedModifier", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UntitledRpgLogic.Core.Models.ModifierDefinition", "ModifierDefinition")
                        .WithMany()
                        .HasForeignKey("ModifierDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("ModifierDefinition");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.EntityInventory", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UntitledRpgLogic.Core.Models.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.EntitySkills", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UntitledRpgLogic.Core.Models.InstancedSkill", "InstancedSkill")
                        .WithMany()
                        .HasForeignKey("InstancedSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("InstancedSkill");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.EntityStats", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UntitledRpgLogic.Core.Models.InstancedStat", "InstancedStat")
                        .WithMany()
                        .HasForeignKey("InstancedStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("InstancedStat");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.InstancedSkill", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.SkillDefinition", "SkillDefinition")
                        .WithMany()
                        .HasForeignKey("SkillDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillDefinition");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.InstancedStat", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.StatDefinition", "StatDefinition")
                        .WithMany()
                        .HasForeignKey("StatDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatDefinition");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.ItemInstance", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.ItemDefinition", "ItemDefinition")
                        .WithMany()
                        .HasForeignKey("ItemDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UntitledRpgLogic.Core.Models.MaterialDefinition", "PrimaryMaterial")
                        .WithMany()
                        .HasForeignKey("PrimaryMaterialId");

                    b.Navigation("ItemDefinition");

                    b.Navigation("PrimaryMaterial");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.LinkedStats", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.StatDefinition", "DependentStat")
                        .WithMany()
                        .HasForeignKey("DependentStatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UntitledRpgLogic.Core.Models.StatDefinition", "LinkedStat")
                        .WithMany()
                        .HasForeignKey("LinkedStatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UntitledRpgLogic.Core.Models.StatDefinition", null)
                        .WithMany("LinkedStats")
                        .HasForeignKey("StatDefinitionId");

                    b.Navigation("DependentStat");

                    b.Navigation("LinkedStat");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.ModifierDefinition", b =>
                {
                    b.HasOne("UntitledRpgLogic.Core.Models.ModificationEffect", "ModifierEffect")
                        .WithMany()
                        .HasForeignKey("ModifierEffectId");

                    b.HasOne("UntitledRpgLogic.Core.Models.ModificationEffect", "StackEffect")
                        .WithMany()
                        .HasForeignKey("StackEffectId");

                    b.Navigation("ModifierEffect");

                    b.Navigation("StackEffect");
                });

            modelBuilder.Entity("UntitledRpgLogic.Core.Models.StatDefinition", b =>
                {
                    b.Navigation("LinkedStats");
                });
#pragma warning restore 612, 618
        }
    }
}
