using UntitledRpgLogic.Core.Enums;
using UntitledRpgLogic.Core.Interfaces;

namespace UntitledRpgLogic.Core.Configuration;

/// <summary>
/// Defines a generic type, field, or school of magic (e.g., Fire, Time, Summoning).
/// </summary>
public class MagicTypeConfig : ITomlConfig
{
	/// <summary>
	///     Optional. If provided in TOML, this specific Guid will be used for the magic type.
	///     If omitted, a new Guid will be generated by the game.
	/// </summary>
	public Guid? ExplicitId { get; set; }

	/// <summary>
	///    The name of the magic type (e.g., "Fire", "Time", "Summoning"). This is required.
	/// </summary>
	public string Name { get; set; } = string.Empty;

	/// <summary>
	///   A brief description of the magic type and its characteristics.
	/// </summary>
	public string Description { get; set; } = string.Empty;

	/// <inheritdoc />
	public ConfigType ConfigType => ConfigType.MagicType;
}
