<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  	<!-- Package metadata -->
		<AssemblyName>UntitledRpgLogic.Infrastructure.Configuration.Yaml</AssemblyName>
		<PackageId>UntitledRpgLogic.Infrastructure.Configuration.Yaml</PackageId>
		<RootNamespace>UntitledRpgLogic.Infrastructure.Configuration.Yaml</RootNamespace>
  </PropertyGroup>

</Project>
