name: Continuous Integration

on:
  push:
    branches: [ "next" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main", "next" ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: 📝 Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: ⚙️ Setup .NET 9
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        id: setup-dotnet
        with:
          dotnet-version: 9.0.x

      - name: 🥟 Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest

      - name: 📦 Cache DotNet Workloads
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.dotnet # Path to cache for SDKs and Workloads
          key: ${{ runner.os }}-dotnet-workloads-${{ hashFiles('global.json') }}-${{ steps.setup-dotnet.outputs.dotnet-version }}
          restore-keys: |
            ${{ runner.os }}-dotnet-workloads-

      - name: 📦 Cache NuGet packages
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: 📦 Cache DotNet Tools
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.dotnet/tools # Path to cache for global tools
          key: ${{ runner.os }}-dotnet-tools-${{ hashFiles('.config/dotnet-tools.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-tools-

      - name: 🌳 Install GitVersion
        uses: gittools/actions/gitversion/setup@71a79f7569b981036febd9ce5870f87e069928e7 # v4.3.3
        with:
          versionSpec: '6.x'

      - name: 🔢 Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@71a79f7569b981036febd9ce5870f87e069928e7 # v4.3.3

      - name: 💬 Display Version Info
        run: |
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"

      - name: 📥 Restore dependencies
        run: |
          cd ${{ github.workspace }}
          dotnet workload restore
          dotnet tool restore
          dotnet restore

      - name: 🔨 Build
        run: |
          cd ${{ github.workspace }}
          dotnet build --no-restore

      - name: 🚀 Test
        run: |
          cd ${{ github.workspace }}
          dotnet test --no-build --verbosity normal
